### ISSUE TITLE
webpack-dev-server or something similar

### ISSUE THREAD

**Issue by bkinsey808** [alexpods/angular2-universal-starter#13]
I would love a dev mode that watches files and reloads browser automatically. Ideally this dev mode should not do bundling.

**Comment by alexpods** [comment]
I'm definitely going to implement some live reloading, but it's not in my top priority right now.
The main thing right now is to make all angular2 core API work perfectly in all possible environments. So currently I'm working on routing support (almost done with server side). 

I'll remain this issue open, to return to it later.

**Comment by bkinsey808** [comment]
Awesome, thanks. With live reloading and routing, this project could become one of the most feature complete ng2 projects ever created so far. I'm considering basing my next ng2 project off of it.
