### ISSUE TITLE
live reload is slow 

### ISSUE THREAD

**Issue by bkinsey808** [alexpods/angular2-universal-starter#39]
Seems like bundling is slow and unnecessary in dev mode. Any way to bypass webpack bunding in the dev mode, and just serve the files unbundled?

**Comment by alexpods** [comment]
@bkinsey808 I'm working on this right now. I think some solution will be done in several hours (2 or 3)

**Comment by alexpods** [comment]
@bkinsey808 In #40 rebuilding speed was improved and  I think I can improve it even more. Initial build time still slow though, but I think it's not so important.

Could you check this out? If rebuild speed is still not fast enough, feel free to tell me about it.

**Comment by bkinsey808** [comment]
OH WOW! You did it. You're a smart guy, I need to learn from you. Very dramatic speed increase, now it's just under 2 seconds from save to seeing the change on the screen.
