### ISSUE TITLE
ng2-highcharts issue

### ISSUE THREAD

**Issue by vaseker** [alexpods/angular2-universal-starter#53]
Hello!
Im trying to use `highcharts` via [ng2-highcharts](https://github.com/Bigous/ng2-highcharts) directives, but I stuck with error (`npm run dev`, `NO_WW`, `NO_SS`)
>     ERROR in ./~/ng2-highcharts/ng2-highcharts.ts
    Module parse failed: ./node_modules/ng2-highcharts/ng2-highcharts.ts Line 1: Unexpected token
    You may need an appropriate loader to handle this file type.
    | import {Ng2Highcharts} from './src/directives/ng2-highcharts';
    | export * from './src/directives/ng2-highcharts';
    |

It works well in official `ng2-highcharts` sample.

So Im trying to use it like this:
```typescript
import HighCharts from 'ng2-highcharts/ng2-highcharts';

@Component({
    directives: [HighCharts.directives],
    template: `<div [ng2-highstocks]="chartStock" class="graph"></div>`
})
```

What is wrong?

Thank you.

**Comment by alexpods** [comment]
I think the reason of the error is [this](https://github.com/alexpods/angular2-universal-starter/blob/master/webpack.config.js#L74) and [this](https://github.com/alexpods/angular2-universal-starter/blob/master/webpack.config.js#L154) lines of code. Briefly: typescript loader are not applied to node modules and `.ts` extension has priority over `.js`. 

Possible solutions:
- Set `resolve.extensions` to `['', '.js', '.ts']` (now `.js` extension has priority over `.ts`)
- Use `.js` extension in the import clause. For example:
`import HighCharts from 'ng2-highcharts/ng2-highcharts.js'`

@vaseker Please, try these solutions and tell me the results.

**Comment by vaseker** [comment]
> set resolve.extensions to ['', '.js', '.ts']

Yes, this is it! 

Thank you!
