### ISSUE TITLE
DLL error on npm start

### ISSUE THREAD

**Issue by glebmachine** [alexpods/angular2-universal-starter#67]
I found a reason why i have added `es6-shim`, `es6-promise` and `reflect-metadata` into my previous PR to package.json file.

When i'm run `npm start` i've got the following DLL error:
```
ERROR in dll vendor
Module not found: Error: Cannot resolve module 'es6-shim'
Module not found: Error: Cannot resolve module 'es6-promise'
Module not found: Error: Cannot resolve module 'reflect-metadata'
```

**Comment by glebmachine** [comment]
😍

**Comment by alexpods** [comment]
@glebmachine Thanks! There are still es6-promise, es6-shim dependencies in `typings`. I'll remove them later when I update `typings` to 1.x
